
###################################### Navigation english ######################################

[[main]]
identifier = "surfboard"
name = "Surfboard"
weight = 1

  [[main]]
  identifier = "surfboard_accessories"
  parent = "surfboard"
  name = "Accessories"
  url = "products/surfboard/accessories/"
  weight = 1

  [[main]]
  identifier = "deck_grip"
  parent = "surfboard"
  name = "Deck Grip"
  url = "products/surfboard/deck-grip/"
  weight = 2

  [[main]]
  identifier = "fins"
  parent = "surfboard"
  name = "Fins"
  url = "products/surfboard/fins/"
  weight = 3

  [[main]]
  identifier = "used_surfboards"
  parent = "surfboard"
  name = "Used Surfboards"
  url = "products/surfboard/used-surfboards/"
  weight = 4

[[main]]
identifier = "wetsuits"
name = "Wetsuits"
url = "products/wetsuits/"
weight = 2

  [[main]]
  identifier = "repair"
  parent = "wetsuits"
  name = "Wetsuit Repair"
  url = "products/wetsuits/repair/"
  weight = 1

  [[main]]
  identifier = "surf_hats"
  parent = "wetsuits"
  name = "Surf Hats"
  url = "products/wetsuits/surf-hats/"
  weight = 2

[[main]]
identifier = "mens"
name = "Mens"
url = "products/mens/"
weight = 3

  [[main]]
  identifier = "mens_tees_tops"
  parent = "mens"
  name = "Mens Tees & Tops"
  url = "products/mens/tees-tops/"
  weight = 1

[[main]]
identifier = "womans"
name = "Womans"
url = "products/womans/"
weight = 4

  [[main]]
  identifier = "womans_tees_tops"
  parent = "womans"
  name = "Womans Tees & Tops"
  url = "products/womans/tees-tops/"
  weight = 1

[[main]]
identifier = "childrens"
name = "Childrens"
url = "products/childrens/"
weight = 5

  [[main]]
  identifier = "childrens_tees_tops"
  parent = "childrens"
  name = "Childrens Tees & Tops"
  url = "products/childrens/tees-tops/"
  weight = 1

[[main]]
identifier = "watches"
name = "Watches"
url = "products/watches/"
weight = 6

  [[main]]
  identifier = "black_watch"
  parent = "watches"
  name = "Black Watches"
  url = "products/watches/black-watch/"
  weight = 1

  [[main]]
  identifier = "other_watch"
  parent = "watches"
  name = "Other Watches"
  url = "products/watches/other-watch/"
  weight = 2

[[main]]
name = "Services"
url = "/services/"
weight = 7

[[main]]
name = "Blog"
url = "https://epiclines.nz/blog/"
weight = 8

[[main]]
name = "About"
url = "https://epiclines.nz/about/"
weight = 9

[[main]]
name = "Review"
url = "/#testimonial"
weight = 10

[[main]]
name = "Contact"
url = "https://epiclines.nz/contact/"
weight = 11






# add params.newTab = true to any menu item you want to be opened in a new tab.






# footer menu
[[footer]]
name = "Blog"
url = "https://epiclines.nz/blog/"
weight = 1

[[footer]]
name = "Contact"
url = "https://epiclines.nz/contact/"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
