
###################################### Navigation english ######################################

[[main]]
identifier = "shop"
name = "Shop"
url = "products/"
weight = 1

  [[main]]
  identifier = "shop_leashes"
  parent = "shop"
  name = "Leash"
  url = "products/leash/"
  weight = 1

  [[main]]
  identifier = "shop_surfboard_racks"
  parent = "shop"
  name = "Surfboard Racks"
  url = "products/surfboard-rack/"
  weight = 2

  [[main]]
  identifier = "shop_deck_grip"
  parent = "shop"
  name = "Deck Grip"
  url = "products/deck-grip/"
  weight = 3

  [[main]]
  identifier = "shop_wax"
  parent = "shop"
  name = "Wax"
  url = "products/wax/"
  weight = 4

  [[main]]
  identifier = "shop_clothing"
  parent = "shop"
  name = "Clothing"
  url = "products/clothing/"
  weight = 5

  [[main]]
  identifier = "shop_board_bags"
  parent = "shop"
  name = "Board Bags"
  url = "products/board-bag/"
  weight = 6

  [[main]]
  identifier = "shop_accessories"
  parent = "shop"
  name = "Accessories"
  url = "products/accessory/"
  weight = 7

  [[main]]
  identifier = "shop_surfboards"
  parent = "shop"
  name = "Surfboards"
  url = "products/surfboard/"
  weight = 8

  [[main]]
  identifier = "shop_fins"
  parent = "shop"
  name = "Fins"
  url = "products/fin/"
  weight = 9


[[main]]
name = "Services"
url = "/#services"
weight = 2

[[main]]
identifier = "resources"
name = "Resources"
weight = 3

  [[main]]
  identifier = "blog"
  parent = "resources"
  name = "Blog"
  url = "https://epiclines.nz/blog/"
  weight = 1

  [[main]]
  identifier = "about"
  parent = "resources"
  name = "About"
  url = "https://epiclines.nz/about/"
  weight = 2

  [[main]]
  identifier = "contact"
  parent = "resources"
  name = "Contact"
  url = "https://epiclines.nz/contact/"
  weight = 3

  [[main]]
  identifier = "review"
  parent = "resources"
  name = "Testimonials"
  url = "/#testimonial"
  weight = 4

  # Todo: Implement https://www.uccmotorhomes.co.nz/review
  # [[main]]
  # identifier = "leave_review"
  # parent = "resources"
  # name = "Leave a Review"
  # url = "/#"
  # weight = 5

  # Todo: Implement
  # [[main]]
  # identifier = "fitness"
  # parent = "resources"
  # name = "Fitness"
  # url = "http://localhost:1313/blog/" with some type of surf fitness taxonomy or even tag.
  # weight = 6

  [[main]]
  identifier = "terms_conditions"
  parent = "resources"
  name = "Terms & Conditions"
  url = "terms-conditions/"
  weight = 7





# add params.newTab = true to any menu item you want to be opened in a new tab.






# footer menu
[[footer]]
name = "Blog"
url = "https://epiclines.nz/blog/"
weight = 1

[[footer]]
name = "Contact"
url = "https://epiclines.nz/contact/"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 3

